name: Integration testing

on:
  push:
    branches:
      - "**"

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Configure Java"
        uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: 21

      - name: "Gradle - Tests"
        uses: "gradle/actions/setup-gradle@v3"
        with:
          arguments: "test --configuration-cache --build-cache --no-watch-fs --stacktrace --scan"

